// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Devspark_core_console_app
{
    public partial class ProgressPredict
    {
        /// <summary>
        /// model input class for ProgressPredict.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ModuleId")]
            public float ModuleId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"CourseId")]
            public float CourseId { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Title")]
            public string Title { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Description")]
            public string Description { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"ProgressStatusEnum")]
            public float ProgressStatusEnum { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProgressPredict.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ModuleId")]
            public float ModuleId { get; set; }

            [ColumnName(@"CourseId")]
            public float CourseId { get; set; }

            [ColumnName(@"Title")]
            public float[] Title { get; set; }

            [ColumnName(@"Description")]
            public float[] Description { get; set; }

            [ColumnName(@"ProgressStatusEnum")]
            public float ProgressStatusEnum { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ProgressPredict.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
