
// This file was auto-generated by ML.NET Model Builder. 

using Devspark_core_console_app;

// Create single instance of sample data from first line of dataset for model input
ProgressPredict.ModelInput sampleData = new ProgressPredict.ModelInput()
{
    ModuleId = 149F,
    CourseId = 46F,
    Title = @"DOM Manipulation",
    Description = @"Basics of interacting with and manipulating the Document Object Model (DOM).",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual ProgressStatusEnum with predicted ProgressStatusEnum from sample data...\n\n");


Console.WriteLine($"ModuleId: {149F}");
Console.WriteLine($"CourseId: {46F}");
Console.WriteLine($"Title: {@"DOM Manipulation"}");
Console.WriteLine($"Description: {@"Basics of interacting with and manipulating the Document Object Model (DOM)."}");
Console.WriteLine($"ProgressStatusEnum: {1F}");


var predictionResult = ProgressPredict.Predict(sampleData);
Console.WriteLine($"\n\nPredicted ProgressStatusEnum: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

